name: 🚀 On push to main

on:
 push:
  branches:
    - main
 workflow_dispatch:

permissions:
 contents: write
 packages: write

jobs:
 tag-and-build:
  name: 🔖 Tag and Build
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate version
      id: version
      run: |
        # Pega última tag ou começa com v1.0.0
        LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        echo "Latest tag: $LATEST_TAG"
        
        # Incrementa versão patch (v1.0.0 -> v1.0.1)
        NEW_VERSION=$(echo $LATEST_TAG | sed 's/v//' | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
        NEW_TAG="v$NEW_VERSION"
        
        echo "New tag: $NEW_TAG"
        echo "tag=$NEW_TAG" >> $GITHUB_OUTPUT

    - name: Create and push tag
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag ${{ steps.version.outputs.tag }}
        git push origin ${{ steps.version.outputs.tag }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        push: true
        file: ./Dockerfile
        target: final
        platforms: linux/amd64,linux/arm64
        tags: |
          ghcr.io/igorlucas/rinha-backend-2025-dotnet:${{ steps.version.outputs.tag }}
          ghcr.io/igorlucas/rinha-backend-2025-dotnet:latest

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version.outputs.tag }}
        release_name: Release ${{ steps.version.outputs.tag }}
        body: |
          🚀 **Automated Release**
          
          - Docker image: `ghcr.io/${{ github.repository_owner }}/rinha-backend-2025-dotnet:${{ steps.version.outputs.tag }}`
          - Built from commit: ${{ github.sha }}
        draft: false
        prerelease: false